# -*- coding: utf-8 -*-
"""Travel_Destination_Extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHd8pCdcHCf58LptEGPVLMJyyIPSh2CR
"""

!pip install transformers==4.30.2 torch

from transformers import pipeline

ner = pipeline(
    "ner",
    aggregation_strategy="simple"
)

travel_blog = """
My journey began in New Delhi, where I boarded a flight to Istanbul.
After spending two days exploring the historic Hagia Sophia and the Grand Bazaar,
I continued my trip to Paris, the city of lights. Walking along the Seine River
and visiting the Eiffel Tower was a dream come true.

From Paris, I took a train to Rome, where ancient history comes alive through
the Colosseum and the Vatican City. I also made a short stop in Florence to admire
the art galleries and architecture before heading north to Switzerland.
The Swiss Alps near Interlaken offered breathtaking views and peaceful landscapes.

Next, my adventure took me to Asia. I relaxed on the beaches of Bali and explored
the temples of Ubud. From Indonesia, I flew to Tokyo, where modern technology blends
seamlessly with traditional culture. A short train ride later, I arrived in Kyoto
to visit ancient shrines and cherry blossom gardens.

The final leg of my journey was in the United States. I spent time in New York,
walking through Central Park and Times Square, before traveling to San Francisco
to see the Golden Gate Bridge. My trip concluded with a brief stop in Dubai, where
the skyline and desert safari left a lasting impression.

"""

entities = ner(travel_blog)

locations = [
    ent["word"] for ent in entities
    if ent["entity_group"] == "LOC"
]

print("Extracted Travel Destinations:")
for loc in set(locations):
    print("-", loc)